### ISSUE TITLE
plug profile is wrong

### ISSUE THREAD

**Issue by andysc** [DynamicDevices/Tasmota#3]
When I configure a SmartPlug using trampoline, it comes up as a `GoSund UP111`.
Most of the plugs we now have are "2NICE" brand. 
I don't know if the profiles are identical (maybe we should check and see?), but it would be good to change the default to 
`2NICE UP111`

**Comment by ajlennon** [comment]
Changed in https://github.com/DynamicDevices/Tasmota/commit/91ebe77df13d8ad17b47a673da65506c53a30e5b
