### ISSUE TITLE
OTA URL in base image is wrong

### ISSUE THREAD

**Issue by andysc** [DynamicDevices/Tasmota#6]
Despite OTA_URL being set to `http://dl.kettlecompanion.com/prod/tasmota-minimal-trampoline.bin.gz` in 
`https://github.com/DynamicDevices/Tasmota/blob/kettlecompanion/tasmota/user_config_override.h`
it still shows the tasmota one 
`http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin.gz`

**Comment by ajlennon** [comment]
Is this still the case with the latest release?

**Comment by andysc** [comment]
fixed in most recent firmware
