### ISSUE TITLE
device name is confusing

### ISSUE THREAD

**Issue by andysc** [DynamicDevices/Tasmota#7]
Device name is currently set to `KettleCompanion`
but we've agreed that's the name of the little kettle, so we need to call it something else.
Suggest `KC_SmartPlug` but am open to suggestions.

This only became apparent when I was writing the configuration instructions, and I was talking about KettleCompanion SSID for the SmartPlug, and thought _dat's not right_.

**Comment by andysc** [comment]
I realise I mean the SSID it shows in AP mode.

**Comment by ajlennon** [comment]
I think this is addressed. AP comes up as `SmartPlug_FactoryDefault` and I've changed the friendly name
